name: TDA Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        TDU_GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        TDU_GITHUB_ENTERPRISE_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: npm test